/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import {
  Button,
  Platform,
  SafeAreaView,
  StatusBar,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import RnNotification from 'react-native-rn-notification-v1';

export default App = () => {
  const handleNotificationClick = () => {
    if (Platform.OS === 'android') {
      RnNotification.createNotificationChannel(
        'CircleChannelId',
        'Circle',
        4,
        'Example',
      );
    }

    RnNotification.showNotification(
      'CircleChannelId',
      'Example Title',
      'Example Body',
    );
  };

  return (
    <SafeAreaView style={styles.outerContainer}>
      <StatusBar barStyle={'dark-content'} />
      <View style={styles.innerContainer}>
        <Button title={'Show Notification'} onPress={handleNotificationClick} />
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
